name: 🪲 Redot CPP
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  REDOT_BASE_BRANCH: 4.3
  # Used for the godot-cpp checkout.
  REDOT_CPP_BRANCH: '4.3'

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-cpp-tests
  cancel-in-progress: true

jobs:
  redot-cpp-tests:
    runs-on: ubuntu-24.04
    name: Build and test Redot CPP
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      # Checkout godot-cpp
      - name: Checkout godot-cpp
        uses: actions/checkout@v4
        with:
          repository: Redot-Engine/redot-cpp
          ref: ${{ env.REDOT_CPP_BRANCH }}
          submodules: 'recursive'
          path: 'redot-cpp'

      # Download generated API dump
      - name: Download GDExtension interface and API dump
        uses: ./.github/actions/download-artifact
        with:
          name: 'godot-api-dump'
          path: './redot-api'

      # Extract and override existing files with generated files
      - name: Extract GDExtension interface and API dump
        run: |
          cp -f redot-api/gdextension_interface.h redot-cpp/gdextension/
          cp -f redot-api/extension_api.json redot-cpp/gdextension/

      # TODO: Add caching to the SCons build and store it for CI via the godot-cache
      # action.

      # Build redot-cpp test extension
      - name: Build redot-cpp test extension
        run: |
          cd redot-cpp/test
          scons target=template_debug dev_build=yes
          cd ../..
